version: '3.9'
services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    user: root
    privileged: true
    environment:
      TZ: "Asia/Seoul"
      JAVA_OPTS: "-Dhudson.model.DownloadService.noSignatureCheck=true"
    ports:
      - "8080:8080"
      - "50000":"50000"
    volumes:
      - "/home/ubuntu/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
